services:
  traefik:
    image: traefik:v3.4
    command:
      # API Traefik (à désactiver en prod ou sécuriser)
      - --api.insecure=true

      # Docker provider
      - --providers.docker=true
      - --providers.file.filename=/certs/traefik-tls.yml
      # - --providers.docker.exposedbydefault=false

      # Entrypoints HTTP & HTTPS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true
      - --entrypoints.websecure.address=:443

      # ACME (Let's Encrypt)
      # - --certificatesresolvers.le.acme.email=simon.botte@icloud.com
      # - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./certs:/certs:ro
    networks:
      web:
        aliases:
          - musikk.localhost

  front:
    container_name: musikk_front
    build:
      context: ../front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`musikk.localhost`)"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
    volumes:
      - ../front:/app
      - front_node_modules:/app/node_modules
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem:ro
    environment:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/rootCA.pem
    working_dir: /app
    command: yarn dev --host
    extra_hosts:
      - "musikk.localhost:host-gateway"
      - "api.musikk.localhost:host-gateway"
      - "host.docker.internal:host-gateway"
    networks:
      - web

  api:
    container_name: musikk_api
    build:
      context: ../api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.musikk.localhost`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      # Middlewares
      - "traefik.http.routers.api.middlewares=api-cors@docker"
      - "traefik.http.middlewares.api-cors.headers.accesscontrolalloworiginlist=https://musikk.localhost"
      - "traefik.http.middlewares.api-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.api-cors.headers.accesscontrolallowheaders=Content-Type,Authorization"
      - "traefik.http.middlewares.api-cors.headers.accesscontrolallowcredentials=true"
    volumes:
      - ../api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"
    command: >
      sh -c "composer install --no-interaction && php -S 0.0.0.0:8000 -t public"
    networks:
      - web

  phpmyadmin:
    container_name: musikk_phpmyadmin
    image: arm64v8/phpmyadmin
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`db.localhost`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - web

  db:
    container_name: musikk_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

volumes:
  db_data:
  front_node_modules:

networks:
  web:
    driver: bridge
