services:
  nginx:
    image: nginx:alpine
    container_name: musikk_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs:ro
    depends_on:
      - front
      - api
      - phpmyadmin
    networks:
      - web

  front:
    container_name: musikk_front
    build:
      context: ../front
    volumes:
      - ../front:/app
      - front_node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev --host 0.0.0.0
    networks:
      - web

  api:
    container_name: musikk_api
    build:
      context: ../api
      dockerfile: Dockerfile
    volumes:
      - ../api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony"
    command: >
      sh -c "composer install --no-interaction && php -S 0.0.0.0:8000 -t public"
    networks:
      - web

  phpmyadmin:
    container_name: musikk_phpmyadmin
    image: arm64v8/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - web

  db:
    container_name: musikk_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

volumes:
  db_data:
  front_node_modules:

networks:
  web:
    driver: bridge
